"""
Converts a knowledge base dict into a well-structured Markdown document.
This is the final output format for Layer 1.
"""
from datetime import datetime


def _confidence_badge(score: float) -> str:
    """Return a text badge for a confidence score."""
    if score >= 0.85:
        return f"`{score:.2f}` ✓ high"
    elif score >= 0.6:
        return f"`{score:.2f}` ~ medium"
    else:
        return f"`{score:.2f}` ✗ low"


def _confidence_bar(score: float, width: int = 10) -> str:
    filled = round(score * width)
    return "█" * filled + "░" * (width - filled)


def to_markdown(kb_data: dict) -> str:
    """
    Convert a knowledge base dict to a structured Markdown string.
    """
    lines: list[str] = []

    platform = kb_data.get("platform_name", "Unknown Platform")
    artifact_type = kb_data.get("artifact_type", "Unknown Artifact")
    description = kb_data.get("artifact_description", "")
    objects = kb_data.get("objects", [])
    dependencies = kb_data.get("dependencies", [])
    validation_rules = kb_data.get("validation_rules", [])
    common_patterns = kb_data.get("common_patterns", [])
    gaps = kb_data.get("gaps", [])
    metadata = kb_data.get("metadata", {})

    # Compute overall confidence
    scores = []
    for obj in objects:
        scores.append(obj.get("confidence", 1.0))
        for f in obj.get("fields", []):
            scores.append(f.get("confidence", 1.0))
    for rule in validation_rules:
        scores.append(rule.get("confidence", 1.0))
    overall = sum(scores) / len(scores) if scores else 0.0

    # -----------------------------------------------------------------------
    # Header
    # -----------------------------------------------------------------------
    lines.append(f"# Knowledge Base: {platform}")
    lines.append("")
    lines.append(f"> **Generated by LikeMinds Layer 1** · {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("")

    # -----------------------------------------------------------------------
    # Overview
    # -----------------------------------------------------------------------
    lines.append("## Overview")
    lines.append("")
    lines.append(f"| | |")
    lines.append(f"|---|---|")
    lines.append(f"| **Platform** | {platform} |")
    lines.append(f"| **Artifact Type** | {artifact_type} |")
    lines.append(f"| **Overall Confidence** | {_confidence_bar(overall)} `{overall:.2f}` |")
    lines.append(f"| **Objects** | {len(objects)} |")
    total_fields = sum(len(o.get("fields", [])) for o in objects)
    lines.append(f"| **Total Fields** | {total_fields} |")
    lines.append(f"| **Validation Rules** | {len(validation_rules)} |")
    lines.append(f"| **Open Gaps** | {len(gaps)} |")
    lines.append("")

    if description:
        lines.append("### Description")
        lines.append("")
        lines.append(description)
        lines.append("")

    # -----------------------------------------------------------------------
    # Objects
    # -----------------------------------------------------------------------
    if objects:
        lines.append("---")
        lines.append("")
        lines.append("## Objects")
        lines.append("")

        for obj in objects:
            obj_name = obj.get("name", "Unnamed")
            obj_desc = obj.get("description", "")
            obj_conf = obj.get("confidence", 1.0)
            obj_rels = obj.get("relationships", [])
            fields = obj.get("fields", [])

            lines.append(f"### {obj_name}")
            lines.append("")
            lines.append(f"**Confidence:** {_confidence_badge(obj_conf)}")
            if obj_desc:
                lines.append("")
                lines.append(obj_desc)
            if obj_rels:
                lines.append("")
                lines.append(f"**Relationships:** {', '.join(obj_rels)}")
            lines.append("")

            if fields:
                lines.append("#### Fields")
                lines.append("")
                lines.append("| Field Path | Type | Required | Confidence | Description |")
                lines.append("|---|---|:---:|---|---|")
                for f in fields:
                    path = f.get("field_path", "")
                    dtype = f.get("data_type", "")
                    req = "Yes" if f.get("required") else "No"
                    conf = f.get("confidence", 1.0)
                    conf_str = f"`{conf:.2f}`"
                    desc = f.get("description", "").replace("|", "\\|").replace("\n", " ")
                    lines.append(f"| `{path}` | {dtype} | {req} | {conf_str} | {desc} |")
                lines.append("")

                # Detail blocks for fields with non-trivial info
                for f in fields:
                    valid_vals = f.get("valid_values", [])
                    constraints = f.get("constraints", [])
                    default = f.get("default_value")
                    depends = f.get("depends_on")
                    source = f.get("source", "")

                    has_detail = valid_vals or constraints or default or depends
                    if not has_detail:
                        continue

                    path = f.get("field_path", "")
                    lines.append(f"<details><summary><code>{path}</code> — details</summary>")
                    lines.append("")
                    if valid_vals:
                        vals_str = ", ".join(f"`{v}`" for v in valid_vals)
                        lines.append(f"**Valid values:** {vals_str}")
                        lines.append("")
                    if default is not None:
                        lines.append(f"**Default:** `{default}`")
                        lines.append("")
                    if depends:
                        lines.append(f"**Depends on:** `{depends}`")
                        lines.append("")
                    if constraints:
                        lines.append("**Constraints:**")
                        for c in constraints:
                            lines.append(f"- {c}")
                        lines.append("")
                    if source:
                        lines.append(f"**Source:** {source}")
                        lines.append("")
                    lines.append("</details>")
                    lines.append("")

    # -----------------------------------------------------------------------
    # Dependencies
    # -----------------------------------------------------------------------
    if dependencies:
        lines.append("---")
        lines.append("")
        lines.append("## Dependencies")
        lines.append("")
        lines.append("| Source | Relationship | Target | Description |")
        lines.append("|---|---|---|---|")
        for dep in dependencies:
            src = dep.get("source_object", "")
            rel = dep.get("relationship", "")
            tgt = dep.get("target_object", "")
            desc = dep.get("description", "").replace("|", "\\|")
            lines.append(f"| **{src}** | {rel} | **{tgt}** | {desc} |")
        lines.append("")

    # -----------------------------------------------------------------------
    # Validation Rules
    # -----------------------------------------------------------------------
    if validation_rules:
        lines.append("---")
        lines.append("")
        lines.append("## Validation Rules")
        lines.append("")
        for rule in validation_rules:
            rid = rule.get("rule_id", "")
            desc = rule.get("description", "")
            scope = rule.get("scope", [])
            severity = rule.get("severity", "error")
            conf = rule.get("confidence", 1.0)

            severity_icon = "🔴" if severity == "error" else "🟡"
            lines.append(f"### {rid}")
            lines.append("")
            lines.append(f"{severity_icon} **{severity.upper()}** · Confidence: `{conf:.2f}`")
            lines.append("")
            lines.append(desc)
            if scope:
                lines.append("")
                lines.append(f"**Applies to:** {', '.join(f'`{s}`' for s in scope)}")
            lines.append("")

    # -----------------------------------------------------------------------
    # Common Patterns
    # -----------------------------------------------------------------------
    if common_patterns:
        lines.append("---")
        lines.append("")
        lines.append("## Common Patterns")
        lines.append("")
        for pattern in common_patterns:
            name = pattern.get("pattern_name", "Pattern")
            desc = pattern.get("description", "")
            example = pattern.get("example_summary", "")
            lines.append(f"### {name}")
            lines.append("")
            if desc:
                lines.append(desc)
                lines.append("")
            if example:
                lines.append(f"**Example:** {example}")
                lines.append("")

    # -----------------------------------------------------------------------
    # Gaps
    # -----------------------------------------------------------------------
    if gaps:
        lines.append("---")
        lines.append("")
        lines.append("## Open Gaps")
        lines.append("")
        lines.append("The following areas still have unresolved unknowns:")
        lines.append("")

        severity_order = {"blocking": 0, "important": 1, "nice_to_have": 2}
        sorted_gaps = sorted(gaps, key=lambda g: severity_order.get(g.get("severity", "nice_to_have"), 99))

        for gap in sorted_gaps:
            area = gap.get("area", "Unknown area")
            desc = gap.get("description", "")
            sev = gap.get("severity", "nice_to_have")
            sev_icons = {"blocking": "🔴 BLOCKING", "important": "🟡 IMPORTANT", "nice_to_have": "⚪ NICE TO HAVE"}
            sev_label = sev_icons.get(sev, sev)
            lines.append(f"- **{area}** ({sev_label}): {desc}")
        lines.append("")

    # -----------------------------------------------------------------------
    # Metadata footer
    # -----------------------------------------------------------------------
    lines.append("---")
    lines.append("")
    lines.append("## Metadata")
    lines.append("")
    lines.append(f"- **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    if metadata:
        for k, v in metadata.items():
            lines.append(f"- **{k}:** {v}")
    lines.append("")
    lines.append("*This knowledge base was built by LikeMinds Layer 1 and is consumed by Layer 2.*")
    lines.append("")

    return "\n".join(lines)
